Repository tomopy/tomopy, pull requests merged in 2019-03, with the labels that each got.

#375 WIP: CMake build system for TomoPy
  .gitignore
  .travis.yml
  CMakeLists.txt
  MANIFEST.in
  benchmarking/pyctest_tomopy_phantom.py
  benchmarking/pyctest_tomopy_utils.py
  build.py
  cmake/Modules/BuildSettings.cmake
  cmake/Modules/ClangFormat.cmake
  cmake/Modules/Compilers.cmake
  cmake/Modules/FindGPerfTools.cmake
  cmake/Modules/FindMKL.cmake
  cmake/Modules/FindPythonLibsExt.cmake
  cmake/Modules/FindTBB.cmake
  cmake/Modules/Findittnotify.cmake
  cmake/Modules/MacroUtilities.cmake
  cmake/Modules/Options.cmake
  cmake/Modules/Packages.cmake
  cmake/Modules/ProjectSettings.cmake
  config/Makefile.darwin
  config/Makefile.linux
  config/Makefile.windows
  config/Mk.base
  envs/requirements-all.txt
  meta.yaml
  pyctest_tomopy.py
  setup.py
  src/CMakeLists.txt
  src/gridrec.c
  tomopy/__init__.py.in
  tomopy/_fft_loader.py
  tomopy/recon/rotation.py
  tomopy/util/misc.py
Labels: do not merge

#390 NumPy incompatibility and other tweaks
  .appveyor.yml
  README.rst
  tomopy/misc/phantom.py
  tomopy/util/dtype.py
Labels: bug

#383 Demote dxchange to soft dependency
  doc/source/data.rst
  envs/requirements-all.txt
  meta.yaml
  tomopy/misc/npmath.py
  tomopy/prep/alignment.py
  tomopy/recon/rotation.py
  tomopy/util/misc.py
Labels: feature request

#396 Refactor algorithm checking in tomopy.recon.algorithm
  tomopy/recon/algorithm.py
Labels: feature request
